### ISSUE TITLE
Baza is still here

### ISSUE THREAD

**Issue by yegor256** [zerocracy/baza.rb#5]
```
/app/objects/baza.rb:29: previous definition of Baza was here
	/app/vendor/bundle/ruby/3.2.0/gems/baza.rb-0.0.3/lib/baza-rb/version.rb:28:in `<top (required)>'
	/app/vendor/bundle/ruby/3.2.0/gems/baza.rb-0.0.3/lib/baza-rb.rb:29:in `require_relative'
	/app/vendor/bundle/ruby/3.2.0/gems/baza.rb-0.0.3/lib/baza-rb.rb:29:in `<top (required)>'
	<internal:/app/vendor/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	<internal:/app/vendor/ruby-3.2.1/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	/app/j/lib/eva.rb:25:in `<top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.4`
